import re
from typing import Any

# TTP Knowledge Base Mapping
MITRE_TTP_MAPPING = {
    "T1059.001": {
        "name": "PowerShell",
        "tactic": "Execution",
        "keywords": [r"\bpowershell\b", r"\bpwsh\b", r"\bpowershell\.exe\b"],
    },
    "T1059.003": {
        "name": "Windows Command Shell",
        "tactic": "Execution",
        "keywords": [r"\bcmd\b", r"\bcmd\.exe\b"],
    },
    "T1059.004": {
        "name": "Unix Shell",
        "tactic": "Execution",
        "keywords": [r"\bbash\b", r"\bsh\b", r"\bzsh\b"],
    },
    "T1566.001": {
        "name": "Spearphishing Attachment",
        "tactic": "Initial Access",
        "keywords": [
            r"\bphishing\b",
            r"\bmalicious attachment\b",
            r"\bspearphishing\b",
        ],
    },
    "T1190": {
        "name": "Exploit Public-Facing Application",
        "tactic": "Initial Access",
        "keywords": [r"\bexploit\b", r"\bvulnerability\b", r"\bCVE-\d{4}-\d{4,7}\b"],
    },
    "T1071.001": {
        "name": "Web Protocols",
        "tactic": "Command and Control",
        "keywords": [r"\bhttp\b", r"\bhttps\b", r"\bweb shell\b"],
    },
    "T1003": {
        "name": "OS Credential Dumping",
        "tactic": "Credential Access",
        "keywords": [r"\bmimikatz\b", r"\blsass\b", r"\bcredential dumping\b"],
    },
    "T1486": {
        "name": "Data Encrypted for Impact",
        "tactic": "Impact",
        "keywords": [r"\bransomware\b", r"\bencrypt\b"],
    },
}


class MitreMapper:
    """Stateless facade for deterministic ATT&CK mapping and export."""

    @staticmethod
    def extract_mitre_techniques(text: str) -> list[dict[str, Any]]:
        return extract_mitre_techniques(text)

    @staticmethod
    def generate_navigator_layer(
        techniques: list[dict[str, Any]],
        layer_name: str = "Hermes CTI Campaign Layer",
    ) -> dict[str, Any]:
        return generate_navigator_layer(techniques, layer_name)


def extract_mitre_techniques(text: str) -> list[dict[str, Any]]:
    techniques: list[dict[str, Any]] = []
    text_lower = text.lower()
    for tech_id, details in MITRE_TTP_MAPPING.items():
        matched_phrases = []
        for kw in details["keywords"]:
            matches = re.findall(kw, text_lower, re.IGNORECASE)
            if matches:
                matched_phrases.extend(matches)

        if matched_phrases:
            techniques.append(
                {
                    "tactic": details["tactic"],
                    "technique_id": tech_id,
                    "technique_name": details["name"],
                    "matched_phrases": sorted(list(set(matched_phrases))),
                }
            )

    # Sort by technique ID for deterministic output
    return sorted(techniques, key=lambda x: x["technique_id"])


def generate_navigator_layer(
    techniques: list[dict[str, Any]], layer_name: str = "Hermes CTI Campaign Layer"
) -> dict[str, Any]:
    layer_techniques = []
    for tech in techniques:
        layer_techniques.append(
            {
                "techniqueID": tech["technique_id"],
                "tactic": tech["tactic"].lower().replace(" ", "-"),
                "score": 100,
                "color": "#e60d0d",
                "comment": f"Detected phrases: "
                f"{', '.join(tech.get('matched_phrases', []))}",
                "enabled": True,
            }
        )

    return {
        "name": layer_name,
        "versions": {"attack": "15", "navigator": "4.5", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Generated by Hermes CTI analysis engine.",
        "techniques": layer_techniques,
    }
